<?php
$region['Algeria'] 											= array('code'=>'DZ', 'cont'=>'002', 'sub'=>'015');
$region['Egypt'] 											= array('code'=>'EG', 'cont'=>'002', 'sub'=>'015');
$region['Western Sahara'] 									= array('code'=>'EH', 'cont'=>'002', 'sub'=>'015');
$region['Libya'] 											= array('code'=>'LY', 'cont'=>'002', 'sub'=>'015');
$region['Morocco'] 											= array('code'=>'MA', 'cont'=>'002', 'sub'=>'015');
$region['Sudan'] 											= array('code'=>'SD', 'cont'=>'002', 'sub'=>'015');
$region['Tunisia'] 											= array('code'=>'TN', 'cont'=>'002', 'sub'=>'015');
$region['Burkina Faso'] 									= array('code'=>'BF', 'cont'=>'002', 'sub'=>'011');
$region['Benin'] 											= array('code'=>'BJ', 'cont'=>'002', 'sub'=>'011');
$region['Côte d\'Ivoire'] 									= array('code'=>'CI', 'cont'=>'002', 'sub'=>'011');
$region['Cape Verde'] 										= array('code'=>'CV', 'cont'=>'002', 'sub'=>'011');
$region['Ghana'] 											= array('code'=>'GH', 'cont'=>'002', 'sub'=>'011');
$region['Gambia'] 											= array('code'=>'GM', 'cont'=>'002', 'sub'=>'011');
$region['Guinea'] 											= array('code'=>'GN', 'cont'=>'002', 'sub'=>'011');
$region['Guinea-Bissau'] 									= array('code'=>'GW', 'cont'=>'002', 'sub'=>'011');
$region['Liberia'] 											= array('code'=>'LR', 'cont'=>'002', 'sub'=>'011');
$region['Mali'] 											= array('code'=>'ML', 'cont'=>'002', 'sub'=>'011');
$region['Mauritania'] 										= array('code'=>'MR', 'cont'=>'002', 'sub'=>'011');
$region['Niger'] 											= array('code'=>'NE', 'cont'=>'002', 'sub'=>'011');
$region['Nigeria'] 											= array('code'=>'NG', 'cont'=>'002', 'sub'=>'011');
$region['Saint Helena'] 									= array('code'=>'SH', 'cont'=>'002', 'sub'=>'011');
$region['Saint Helena, Ascension and Tristan da Cunha'] 	= array('code'=>'SH', 'cont'=>'002', 'sub'=>'011');
$region['Sierra Leone'] 									= array('code'=>'SL', 'cont'=>'002', 'sub'=>'011');
$region['Senegal'] 											= array('code'=>'SN', 'cont'=>'002', 'sub'=>'011');
$region['Togo'] 											= array('code'=>'TG', 'cont'=>'002', 'sub'=>'011');
$region['Angola'] 											= array('code'=>'AO', 'cont'=>'002', 'sub'=>'017');
$region['Congo'] 											= array('code'=>'CD', 'cont'=>'002', 'sub'=>'017');
$region['Congo, the Democratic Republic of the'] 			= array('code'=>'CD', 'cont'=>'002', 'sub'=>'017');
$region['Zaire'] 											= array('code'=>'ZR', 'cont'=>'002', 'sub'=>'017');
$region['Central African Republic'] 						= array('code'=>'CF', 'cont'=>'002', 'sub'=>'017');
$region['Congo'] 											= array('code'=>'CG', 'cont'=>'002', 'sub'=>'017');
$region['Cameroon'] 										= array('code'=>'CM', 'cont'=>'002', 'sub'=>'017');
$region['Gabon'] 											= array('code'=>'GA', 'cont'=>'002', 'sub'=>'017');
$region['Equatorial Guinea'] 								= array('code'=>'GQ', 'cont'=>'002', 'sub'=>'017');
$region['Sao Tome and Principe'] 							= array('code'=>'ST', 'cont'=>'002', 'sub'=>'017');
$region['Chad'] 											= array('code'=>'TD', 'cont'=>'002', 'sub'=>'017');
$region['Burundi'] 											= array('code'=>'BI', 'cont'=>'002', 'sub'=>'014');
$region['Djibouti'] 										= array('code'=>'DJ', 'cont'=>'002', 'sub'=>'014');
$region['Eritrea'] 											= array('code'=>'ER', 'cont'=>'002', 'sub'=>'014');
$region['Ethiopia'] 										= array('code'=>'ET', 'cont'=>'002', 'sub'=>'014');
$region['Kenya'] 											= array('code'=>'KE', 'cont'=>'002', 'sub'=>'014');
$region['Comoros'] 											= array('code'=>'KM', 'cont'=>'002', 'sub'=>'014');
$region['Madagascar'] 										= array('code'=>'MG', 'cont'=>'002', 'sub'=>'014');
$region['Mauritius'] 										= array('code'=>'MU', 'cont'=>'002', 'sub'=>'014');
$region['Malawi'] 											= array('code'=>'MW', 'cont'=>'002', 'sub'=>'014');
$region['Mozambique'] 										= array('code'=>'MZ', 'cont'=>'002', 'sub'=>'014');
$region['Réunion'] 											= array('code'=>'RE', 'cont'=>'002', 'sub'=>'014');
$region['Rwanda'] 											= array('code'=>'RW', 'cont'=>'002', 'sub'=>'014');
$region['Seychelles'] 										= array('code'=>'SC', 'cont'=>'002', 'sub'=>'014');
$region['Somalia'] 											= array('code'=>'SO', 'cont'=>'002', 'sub'=>'014');
$region['Tanzania'] 										= array('code'=>'TZ', 'cont'=>'002', 'sub'=>'014');
$region['Tanzania, United Republic of'] 					= array('code'=>'TZ', 'cont'=>'002', 'sub'=>'014');
$region['Uganda'] 											= array('code'=>'UG', 'cont'=>'002', 'sub'=>'014');
$region['Mayotte'] 											= array('code'=>'YT', 'cont'=>'002', 'sub'=>'014');
$region['Zambia'] 											= array('code'=>'ZM', 'cont'=>'002', 'sub'=>'014');
$region['Zimbabwe'] 										= array('code'=>'ZW', 'cont'=>'002', 'sub'=>'014');
$region['Botswana'] 										= array('code'=>'BW', 'cont'=>'002', 'sub'=>'018');
$region['Lesotho'] 											= array('code'=>'LS', 'cont'=>'002', 'sub'=>'018');
$region['Namibia'] 											= array('code'=>'NA', 'cont'=>'002', 'sub'=>'018');
$region['Swaziland'] 										= array('code'=>'SZ', 'cont'=>'002', 'sub'=>'018');
$region['South Africa'] 									= array('code'=>'ZA', 'cont'=>'002', 'sub'=>'018');
$region['Guernsey'] 										= array('code'=>'GG', 'cont'=>'150', 'sub'=>'154');
$region['Jersey'] 											= array('code'=>'JE', 'cont'=>'150', 'sub'=>'154');
$region['Åland Islands']									= array('code'=>'AX', 'cont'=>'150', 'sub'=>'154');
$region['Denmark'] 											= array('code'=>'DK', 'cont'=>'150', 'sub'=>'154');
$region['Estonia'] 											= array('code'=>'EE', 'cont'=>'150', 'sub'=>'154');
$region['Finland'] 											= array('code'=>'FI', 'cont'=>'150', 'sub'=>'154');
$region['Faroe Islands'] 									= array('code'=>'FO', 'cont'=>'150', 'sub'=>'154');
$region['United Kingdom'] 									= array('code'=>'GB', 'cont'=>'150', 'sub'=>'154');
$region['Ireland'] 											= array('code'=>'IE', 'cont'=>'150', 'sub'=>'154');
$region['Isle of Man'] 										= array('code'=>'IM', 'cont'=>'150', 'sub'=>'154');
$region['Iceland'] 											= array('code'=>'IS', 'cont'=>'150', 'sub'=>'154');
$region['Lithuania']										= array('code'=>'LT', 'cont'=>'150', 'sub'=>'154');
$region['Latvia'] 											= array('code'=>'LV', 'cont'=>'150', 'sub'=>'154');
$region['Norway'] 											= array('code'=>'NO', 'cont'=>'150', 'sub'=>'154');
$region['Sweden'] 											= array('code'=>'SE', 'cont'=>'150', 'sub'=>'154');
$region['Svalbard and Jan Mayen'] 							= array('code'=>'SJ', 'cont'=>'150', 'sub'=>'154');
$region['Austria'] 											= array('code'=>'AT', 'cont'=>'150', 'sub'=>'155');
$region['Belgium'] 											= array('code'=>'BE', 'cont'=>'150', 'sub'=>'155');
$region['Switzerland'] 										= array('code'=>'CH', 'cont'=>'150', 'sub'=>'155');
$region['Germany'] 											= array('code'=>'DE', 'cont'=>'150', 'sub'=>'155');
$region['DD'] 												= array('code'=>'DD', 'cont'=>'150', 'sub'=>'155');
$region['France']											= array('code'=>'FR', 'cont'=>'150', 'sub'=>'155');
$region['France, Metropolitan'] 							= array('code'=>'FX', 'cont'=>'150', 'sub'=>'155');
$region['Liechtenstein'] 									= array('code'=>'LI', 'cont'=>'150', 'sub'=>'155');
$region['Luxembourg'] 										= array('code'=>'LU', 'cont'=>'150', 'sub'=>'155');
$region['Monaco'] 											= array('code'=>'MC', 'cont'=>'150', 'sub'=>'155');
$region['Netherlands'] 										= array('code'=>'NL', 'cont'=>'150', 'sub'=>'155');
$region['Bulgaria'] 										= array('code'=>'BG', 'cont'=>'150', 'sub'=>'151');
$region['Belarus'] 											= array('code'=>'BY', 'cont'=>'150', 'sub'=>'151');
$region['Czech Republic'] 									= array('code'=>'CZ', 'cont'=>'150', 'sub'=>'151');
$region['Hungary'] 											= array('code'=>'HU', 'cont'=>'150', 'sub'=>'151');
$region['Moldova']				 							= array('code'=>'MD', 'cont'=>'150', 'sub'=>'151');
$region['Moldova, Republic of'] 							= array('code'=>'MD', 'cont'=>'150', 'sub'=>'151');
$region['Poland'] 											= array('code'=>'PL', 'cont'=>'150', 'sub'=>'151');
$region['Romania'] 											= array('code'=>'RO', 'cont'=>'150', 'sub'=>'151');
$region['Russian Federation'] 								= array('code'=>'RU', 'cont'=>'150', 'sub'=>'151');
$region['USSR'] 											= array('code'=>'SU', 'cont'=>'150', 'sub'=>'151');
$region['Slovakia'] 										= array('code'=>'SK', 'cont'=>'150', 'sub'=>'151');
$region['Ukraine'] 											= array('code'=>'UA', 'cont'=>'150', 'sub'=>'151');
$region['Andorra'] 											= array('code'=>'AD', 'cont'=>'150', 'sub'=>'039');
$region['Albania'] 											= array('code'=>'AL', 'cont'=>'150', 'sub'=>'039');
$region['Bosnia and Herzegovina'] 							= array('code'=>'BA', 'cont'=>'150', 'sub'=>'039');
$region['Spain'] 											= array('code'=>'ES', 'cont'=>'150', 'sub'=>'039');
$region['Gibraltar'] 										= array('code'=>'GI', 'cont'=>'150', 'sub'=>'039');
$region['Greece'] 											= array('code'=>'GR', 'cont'=>'150', 'sub'=>'039');
$region['Croatia'] 											= array('code'=>'HR', 'cont'=>'150', 'sub'=>'039');
$region['Italy'] 											= array('code'=>'IT', 'cont'=>'150', 'sub'=>'039');
$region['Montenegro'] 										= array('code'=>'ME', 'cont'=>'150', 'sub'=>'039');
$region['Macedonia'] 										= array('code'=>'MK', 'cont'=>'150', 'sub'=>'039');
$region['Macedonia, the former Yugoslav Republic of'] 		= array('code'=>'MK', 'cont'=>'150', 'sub'=>'039');
$region['Malta'] 											= array('code'=>'MT', 'cont'=>'150', 'sub'=>'039');
$region['Serbia and Montenegro'] 							= array('code'=>'CS', 'cont'=>'150', 'sub'=>'039');
$region['Serbia'] 											= array('code'=>'RS', 'cont'=>'150', 'sub'=>'039');
$region['Portugal'] 										= array('code'=>'PT', 'cont'=>'150', 'sub'=>'039');
$region['Slovenia'] 										= array('code'=>'SI', 'cont'=>'150', 'sub'=>'039');
$region['San Marino'] 										= array('code'=>'SM', 'cont'=>'150', 'sub'=>'039');
$region['Vatican City'] 									= array('code'=>'VA', 'cont'=>'150', 'sub'=>'039');
$region['Holy See (Vatican City State)'] 					= array('code'=>'VA', 'cont'=>'150', 'sub'=>'039');
$region['Yugoslavia'] 										= array('code'=>'YU', 'cont'=>'150', 'sub'=>'039');
$region['Bermuda'] 											= array('code'=>'BM', 'cont'=>'019', 'sub'=>'021');
$region['Canada'] 											= array('code'=>'CA', 'cont'=>'019', 'sub'=>'021');
$region['Greenland'] 										= array('code'=>'GL', 'cont'=>'019', 'sub'=>'021');
$region['Saint Pierre and Miquelon'] 						= array('code'=>'PM', 'cont'=>'019', 'sub'=>'021');
$region['United States'] 									= array('code'=>'US', 'cont'=>'019', 'sub'=>'021');
$region['Antigua and Barbuda'] 								= array('code'=>'AG', 'cont'=>'019', 'sub'=>'029');
$region['Anguilla'] 										= array('code'=>'AI', 'cont'=>'019', 'sub'=>'029');
$region['Netherlands Antilles'] 							= array('code'=>'AN', 'cont'=>'019', 'sub'=>'029');
$region['Aruba'] 											= array('code'=>'AW', 'cont'=>'019', 'sub'=>'029');
$region['Barbados'] 										= array('code'=>'BB', 'cont'=>'019', 'sub'=>'029');
$region['Saint Barthélemy'] 								= array('code'=>'BL', 'cont'=>'019', 'sub'=>'029');
$region['Bahamas'] 											= array('code'=>'BS', 'cont'=>'019', 'sub'=>'029');
$region['Cuba'] 											= array('code'=>'CU', 'cont'=>'019', 'sub'=>'029');
$region['Dominica'] 										= array('code'=>'DM', 'cont'=>'019', 'sub'=>'029');
$region['Dominican Republic'] 								= array('code'=>'DO', 'cont'=>'019', 'sub'=>'029');
$region['Grenada'] 											= array('code'=>'GD', 'cont'=>'019', 'sub'=>'029');
$region['Guadeloupe'] 										= array('code'=>'GP', 'cont'=>'019', 'sub'=>'029');
$region['Haiti'] 											= array('code'=>'HT', 'cont'=>'019', 'sub'=>'029');
$region['Jamaica'] 											= array('code'=>'JM', 'cont'=>'019', 'sub'=>'029');
$region['Saint Kitts and Nevis'] 							= array('code'=>'KN', 'cont'=>'019', 'sub'=>'029');
$region['Cayman Islands'] 									= array('code'=>'KY', 'cont'=>'019', 'sub'=>'029');
$region['Saint Lucia'] 										= array('code'=>'LC', 'cont'=>'019', 'sub'=>'029');
$region['Saint Martin'] 									= array('code'=>'MF', 'cont'=>'019', 'sub'=>'029');
$region['Saint Martin (French part)'] 						= array('code'=>'MF', 'cont'=>'019', 'sub'=>'029');
$region['Martinique'] 										= array('code'=>'MQ', 'cont'=>'019', 'sub'=>'029');
$region['Montserrat'] 										= array('code'=>'MS', 'cont'=>'019', 'sub'=>'029');
$region['Puerto Rico'] 										= array('code'=>'PR', 'cont'=>'019', 'sub'=>'029');
$region['Turks and Caicos Islands'] 						= array('code'=>'TC', 'cont'=>'019', 'sub'=>'029');
$region['Trinidad and Tobago'] 								= array('code'=>'TT', 'cont'=>'019', 'sub'=>'029');
$region['Saint Vincent and the Grenadines'] 				= array('code'=>'VC', 'cont'=>'019', 'sub'=>'029');
$region['Virgin Islands, British'] 							= array('code'=>'VG', 'cont'=>'019', 'sub'=>'029');
$region['Virgin Islands, U.S'] 								= array('code'=>'VI', 'cont'=>'019', 'sub'=>'029');
$region['Belize'] 											= array('code'=>'BZ', 'cont'=>'019', 'sub'=>'013');
$region['Costa Rica'] 										= array('code'=>'CR', 'cont'=>'019', 'sub'=>'013');
$region['Guatemala'] 										= array('code'=>'GT', 'cont'=>'019', 'sub'=>'013');
$region['Honduras'] 										= array('code'=>'HN', 'cont'=>'019', 'sub'=>'013');
$region['Mexico'] 											= array('code'=>'MX', 'cont'=>'019', 'sub'=>'013');
$region['Nicaragua'] 										= array('code'=>'NI', 'cont'=>'019', 'sub'=>'013');
$region['Panama'] 											= array('code'=>'PA', 'cont'=>'019', 'sub'=>'013');
$region['El Salvador'] 										= array('code'=>'SV', 'cont'=>'019', 'sub'=>'013');
$region['Argentina'] 										= array('code'=>'AR', 'cont'=>'019', 'sub'=>'005');
$region['Bolivia'] 											= array('code'=>'BO', 'cont'=>'019', 'sub'=>'005');
$region['Bolivia, Plurinational State of'] 					= array('code'=>'BO', 'cont'=>'019', 'sub'=>'005');
$region['Brazil'] 											= array('code'=>'BR', 'cont'=>'019', 'sub'=>'005');
$region['Chile'] 											= array('code'=>'CL', 'cont'=>'019', 'sub'=>'005');
$region['Colombia'] 										= array('code'=>'CO', 'cont'=>'019', 'sub'=>'005');
$region['Ecuador'] 											= array('code'=>'EC', 'cont'=>'019', 'sub'=>'005');
$region['Falkland Islands (Malvinas)'] 						= array('code'=>'FK', 'cont'=>'019', 'sub'=>'005');
$region['French Guiana'] 									= array('code'=>'GF', 'cont'=>'019', 'sub'=>'005');
$region['Guyana'] 											= array('code'=>'GY', 'cont'=>'019', 'sub'=>'005');
$region['Peru'] 											= array('code'=>'PE', 'cont'=>'019', 'sub'=>'005');
$region['Paraguay'] 										= array('code'=>'PY', 'cont'=>'019', 'sub'=>'005');
$region['Suriname'] 										= array('code'=>'SR', 'cont'=>'019', 'sub'=>'005');
$region['Uruguay'] 											= array('code'=>'UY', 'cont'=>'019', 'sub'=>'005');
$region['Venezuela'] 										= array('code'=>'VE', 'cont'=>'019', 'sub'=>'005');
$region['Venezuela, Bolivarian Republic of'] 				= array('code'=>'VE', 'cont'=>'019', 'sub'=>'005');
$region['Turkmenistan'] 									= array('code'=>'TM', 'cont'=>'142', 'sub'=>'143');
$region['Tajikistan'] 										= array('code'=>'TJ', 'cont'=>'142', 'sub'=>'143');
$region['Kyrgyzstan'] 										= array('code'=>'KG', 'cont'=>'142', 'sub'=>'143');
$region['Kazakhstan'] 										= array('code'=>'KZ', 'cont'=>'142', 'sub'=>'143');
$region['Uzbekistan'] 										= array('code'=>'UZ', 'cont'=>'142', 'sub'=>'143');
$region['China'] 											= array('code'=>'CN', 'cont'=>'142', 'sub'=>'030');
$region['Hong Kong'] 										= array('code'=>'HK', 'cont'=>'142', 'sub'=>'030');
$region['Japan'] 											= array('code'=>'JP', 'cont'=>'142', 'sub'=>'030');
$region['Korea, Democratic People\'s Republic of'] 			= array('code'=>'KP', 'cont'=>'142', 'sub'=>'030');
$region['Korea, Republic of'] 								= array('code'=>'KR', 'cont'=>'142', 'sub'=>'030');
$region['Mongolia'] 										= array('code'=>'MN', 'cont'=>'142', 'sub'=>'030');
$region['Macao'] 											= array('code'=>'MO', 'cont'=>'142', 'sub'=>'030');
$region['Taiwan, Province of China'] 						= array('code'=>'TW', 'cont'=>'142', 'sub'=>'030');
$region['Afghanistan'] 										= array('code'=>'AF', 'cont'=>'142', 'sub'=>'034');
$region['Bangladesh'] 										= array('code'=>'BD', 'cont'=>'142', 'sub'=>'034');
$region['Bhutan'] 											= array('code'=>'BT', 'cont'=>'142', 'sub'=>'034');
$region['India'] 											= array('code'=>'IN', 'cont'=>'142', 'sub'=>'034');
$region['Iran, Islamic Republic of'] 						= array('code'=>'IR', 'cont'=>'142', 'sub'=>'034');
$region['Sri Lanka'] 										= array('code'=>'LK', 'cont'=>'142', 'sub'=>'034');
$region['Maldives'] 										= array('code'=>'MV', 'cont'=>'142', 'sub'=>'034');
$region['Nepal'] 											= array('code'=>'NP', 'cont'=>'142', 'sub'=>'034');
$region['Pakistan'] 										= array('code'=>'PK', 'cont'=>'142', 'sub'=>'034');
$region['Brunei Darussalam'] 								= array('code'=>'BN', 'cont'=>'142', 'sub'=>'035');
$region['Indonesia'] 										= array('code'=>'ID', 'cont'=>'142', 'sub'=>'035');
$region['Cambodia'] 										= array('code'=>'KH', 'cont'=>'142', 'sub'=>'035');
$region['Lao People\'s Democratic Republic'] 				= array('code'=>'LA', 'cont'=>'142', 'sub'=>'035');
$region['Myanmar'] 											= array('code'=>'MM', 'cont'=>'142', 'sub'=>'035');
$region['Burma'] 											= array('code'=>'BU', 'cont'=>'142', 'sub'=>'035');
$region['Malaysia'] 										= array('code'=>'MY', 'cont'=>'142', 'sub'=>'035');
$region['Philippines'] 										= array('code'=>'PH', 'cont'=>'142', 'sub'=>'035');
$region['Singapore'] 										= array('code'=>'SG', 'cont'=>'142', 'sub'=>'035');
$region['Thailand'] 										= array('code'=>'TH', 'cont'=>'142', 'sub'=>'035');
$region['Timor-Leste'] 										= array('code'=>'TL', 'cont'=>'142', 'sub'=>'035');
$region['East Timor'] 										= array('code'=>'TP', 'cont'=>'142', 'sub'=>'035');
$region['Viet Nam'] 										= array('code'=>'VN', 'cont'=>'142', 'sub'=>'035');
$region['United Arab Emirates'] 							= array('code'=>'AE', 'cont'=>'142', 'sub'=>'145');
$region['Armenia'] 											= array('code'=>'AM', 'cont'=>'142', 'sub'=>'145');
$region['Azerbaijan'] 										= array('code'=>'AZ', 'cont'=>'142', 'sub'=>'145');
$region['Bahrain'] 											= array('code'=>'BH', 'cont'=>'142', 'sub'=>'145');
$region['Cyprus'] 											= array('code'=>'CY', 'cont'=>'142', 'sub'=>'145');
$region['Georgia'] 											= array('code'=>'GE', 'cont'=>'142', 'sub'=>'145');
$region['Israel'] 											= array('code'=>'IL', 'cont'=>'142', 'sub'=>'145');
$region['Iraq'] 											= array('code'=>'IQ', 'cont'=>'142', 'sub'=>'145');
$region['Jordan'] 											= array('code'=>'JO', 'cont'=>'142', 'sub'=>'145');
$region['Kuwait'] 											= array('code'=>'KW', 'cont'=>'142', 'sub'=>'145');
$region['Lebanon'] 											= array('code'=>'LB', 'cont'=>'142', 'sub'=>'145');
$region['Oman'] 											= array('code'=>'OM', 'cont'=>'142', 'sub'=>'145');
$region['Palestine, State of'] 								= array('code'=>'PS', 'cont'=>'142', 'sub'=>'145');
$region['Qatar'] 											= array('code'=>'QA', 'cont'=>'142', 'sub'=>'145');
$region['Saudi Arabia'] 									= array('code'=>'SA', 'cont'=>'142', 'sub'=>'145');
$region['Neutral Zone'] 									= array('code'=>'NT', 'cont'=>'142', 'sub'=>'145');
$region['Syrian Arab Republic'] 							= array('code'=>'SY', 'cont'=>'142', 'sub'=>'145');
$region['Turkey'] 											= array('code'=>'TR', 'cont'=>'142', 'sub'=>'145');
$region['Yemen'] 											= array('code'=>'YE', 'cont'=>'142', 'sub'=>'145');
$region['YD'] 												= array('code'=>'YD', 'cont'=>'142', 'sub'=>'145');
$region['Australia'] 										= array('code'=>'AU', 'cont'=>'009', 'sub'=>'053');
$region['Norfolk Island'] 									= array('code'=>'NF', 'cont'=>'009', 'sub'=>'053');
$region['New Zealand'] 										= array('code'=>'NZ', 'cont'=>'009', 'sub'=>'053');
$region['Fiji'] 											= array('code'=>'FJ', 'cont'=>'009', 'sub'=>'054');
$region['New Caledonia'] 									= array('code'=>'NC', 'cont'=>'009', 'sub'=>'054');
$region['Papua New Guinea'] 								= array('code'=>'PG', 'cont'=>'009', 'sub'=>'054');
$region['Solomon Islands'] 									= array('code'=>'SB', 'cont'=>'009', 'sub'=>'054');
$region['Vanuatu'] 											= array('code'=>'VU', 'cont'=>'009', 'sub'=>'054');
$region['Micronesia, Federated States of'] 					= array('code'=>'FM', 'cont'=>'009', 'sub'=>'057');
$region['Guam'] 											= array('code'=>'GU', 'cont'=>'009', 'sub'=>'057');
$region['Kiribati'] 										= array('code'=>'KI', 'cont'=>'009', 'sub'=>'057');
$region['Marshall Islands'] 								= array('code'=>'MH', 'cont'=>'009', 'sub'=>'057');
$region['Northern Mariana Islands'] 						= array('code'=>'MP', 'cont'=>'009', 'sub'=>'057');
$region['Nauru'] 											= array('code'=>'NR', 'cont'=>'009', 'sub'=>'057');
$region['Palau'] 											= array('code'=>'PW', 'cont'=>'009', 'sub'=>'057');
$region['American Samoa'] 									= array('code'=>'AS', 'cont'=>'009', 'sub'=>'061');
$region['Cook Islands'] 									= array('code'=>'CK', 'cont'=>'009', 'sub'=>'061');
$region['Niue'] 											= array('code'=>'NU', 'cont'=>'009', 'sub'=>'061');
$region['French Polynesia'] 								= array('code'=>'PF', 'cont'=>'009', 'sub'=>'061');
$region['Pitcairn'] 										= array('code'=>'PN', 'cont'=>'009', 'sub'=>'061');
$region['Tokelau'] 											= array('code'=>'TK', 'cont'=>'009', 'sub'=>'061');
$region['Tonga'] 											= array('code'=>'TO', 'cont'=>'009', 'sub'=>'061');
$region['Tuvalu'] 											= array('code'=>'TV', 'cont'=>'009', 'sub'=>'061');
$region['Wallis and Futuna'] 								= array('code'=>'WF', 'cont'=>'009', 'sub'=>'061');
$region['Samoa'] 											= array('code'=>'WS', 'cont'=>'009', 'sub'=>'061');
